import { readFile, writeFile } from 'node:fs/promises';

const pkg = JSON.parse((await readFile('./package.json', 'utf8'))) as { version: string };
await writeFile('./src/pkg.ts',
	`/*
	This file is automatically generated by scripts/gen-pkg-ts.ts.
	DO NOT edit this file. To change its behavior, edit scripts/gen-pkg-ts.ts instead.
*/
/* eslint-disable quotes */
/* eslint-disable comma-dangle */
export const pkg = ${ JSON.stringify({
		version: pkg.version,
	}, undefined, '\t')} as const;
`,
);
